In [109]:
import warnings
warnings.simplefilter(action='ignore' , category = FutureWarning)

In [110]:
from sklearn.datasets import load_breast_cancer

import pandas as pd

breast_cancer_data = load_breast_cancer()

df_data = pd.DataFrame(breast_cancer_data.data)

df_labels = pd.DataFrame(breast_cancer_data.target)

In [111]:
print(df_data[0: 10])

      0      1       2       3        4        5        6        7       8   \
0  17.99  10.38  122.80  1001.0  0.11840  0.27760  0.30010  0.14710  0.2419   
1  20.57  17.77  132.90  1326.0  0.08474  0.07864  0.08690  0.07017  0.1812   
2  19.69  21.25  130.00  1203.0  0.10960  0.15990  0.19740  0.12790  0.2069   
3  11.42  20.38   77.58   386.1  0.14250  0.28390  0.24140  0.10520  0.2597   
4  20.29  14.34  135.10  1297.0  0.10030  0.13280  0.19800  0.10430  0.1809   
5  12.45  15.70   82.57   477.1  0.12780  0.17000  0.15780  0.08089  0.2087   
6  18.25  19.98  119.60  1040.0  0.09463  0.10900  0.11270  0.07400  0.1794   
7  13.71  20.83   90.20   577.9  0.11890  0.16450  0.09366  0.05985  0.2196   
8  13.00  21.82   87.50   519.8  0.12730  0.19320  0.18590  0.09353  0.2350   
9  12.46  24.04   83.97   475.9  0.11860  0.23960  0.22730  0.08543  0.2030   

        9   ...     20     21      22      23      24      25      26      27  \
0  0.07871  ...  25.38  17.33  184.60  2019.0  0.

In [112]:
print(df_labels[0:10])

   0
0  0
1  0
2  0
3  0
4  0
5  0
6  0
7  0
8  0
9  0


In [113]:
print(breast_cancer_data.target_names)

['malignant' 'benign']


In [114]:
X_train.shape_input = df_data[:456]
Y_train.shape_target = df_labels[:456]
X_test.shape_input = df_data[456:]
Y_test.shape_target = df_labels[456:]

In [115]:
kn.fit(X_train.shape_input , Y_train.shape_target.values.ravel())

KNeighborsClassifier()

In [116]:
import numpy as np

In [117]:
input_arr = np.array(df_data)
target_arr = np.array(df_labels)

In [118]:
print(input_arr.shape)

(569, 30)


In [119]:
np.random.seed(456)
index = np.arange(569)
np.random.shuffle(index)

In [120]:
print(index)

[ 30 442  16 504 148 324 469 156  15 190 330  25 278 246 214 296  20 375
 164 150 417 258 295 391 338  39 252  64 204 268 393 138 389 311 418 233
 256 201   0 508 558 515 292 116 193  70 309 444 380 474 305 209 424 348
 433 542 132 242 565 187 153 353 308  43 314 447  92 550 531 307  47 257
 506 414 503 215 267 161 304 360 313 537 241 544 344 343 140 410 200   7
  83  46 212 325  94  58 298 223 334 259 496 119  24 489 357 213 513 407
 195 288 245 183 446 368 300 199 141 222  51 405  12 229 273  37 443 131
 554  18 468 566 538 553  54 203 412 420  85 466 189 112 321  50  53 526
 399  91  28 322 568 177  59 402 251 184 188 284 464 217 383 151 532 124
  41 239 487 439 552 481 486 501 567 386 249 535 549  61  55 283 208 563
 232 370 492 275 527 461   8 427  14 529 175 546 163   3 454 216 302 434
 435 179  80 484 168 518 385 415 310  65 130 120 482 361  73 561 350 483
 367 320 115 114 426 162 556 340 160 180 293 299  27 512  52 103 261 337
 263 505 436 369 499 450 392 394  81 129 374 173 52

In [121]:
X_train.shape_input = input_arr[index[:456]]
Y_train.shape_target = target_arr[index[:456]]

In [122]:
X_test.shape_input = input_arr[index[456:]]
Y_test.shape_target = target_arr[index[456:]]

In [123]:
print("X_train.shape :", X_train.shape_input)

print("Y_train.shape :", Y_train.shape_target)

print("X_test.shape:", X_test.shape_input)

print("Y_test.shape:", Y_test.shape_target)

X_train.shape : [[1.863e+01 2.511e+01 1.248e+02 ... 1.848e-01 3.444e-01 9.782e-02]
 [1.378e+01 1.579e+01 8.837e+01 ... 3.312e-02 1.859e-01 6.810e-02]
 [1.468e+01 2.013e+01 9.474e+01 ... 1.609e-01 3.029e-01 8.216e-02]
 ...
 [1.298e+01 1.935e+01 8.452e+01 ... 9.858e-02 3.596e-01 9.166e-02]
 [1.328e+01 1.372e+01 8.579e+01 ... 9.173e-02 2.736e-01 7.320e-02]
 [1.364e+01 1.560e+01 8.738e+01 ... 9.222e-02 2.530e-01 6.510e-02]]
Y_train.shape : [[0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]


In [124]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 3)

In [125]:
knn.fit(X_train.shape_input , Y_train.shape_target.ravel())

KNeighborsClassifier(n_neighbors=3)

In [126]:
knn.score(X_test.shape_input , Y_test.shape_target)

0.9469026548672567